### ISSUE TITLE
Failed to connect database

### ISSUE THREAD

**Issue by Akibalogh** [chasdevs/meetrics#5]
Me again.. any advice for why I can't find the database this time?

```
aki-macbook-pro:meetrics akibalogh$ docker run --rm -e DB_HOST="host.docker.internal" -v `pwd`:/app chasdevs/meetrics | tee out.log
time="2020-04-16T21:47:17Z" level=info msg="Environment: development\n"
panic: failed to connect database

goroutine 1 [running]:
github.com/chasdevs/meetrics/pkg/data.Init()
	/app/pkg/data/data.go:35 +0x18c
main.init.0()
	/app/main.go:27 +0x2e
```

I can run `docker-compose up -d mysql` but not the go program

**Comment by Akibalogh** [comment]
I don't have anything else running

```aki-macbook-pro:meetrics akibalogh$ docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
<none>               <none>              757618972b54        8 minutes ago       1.02GB
akibalogh/meetrics   latest              98d54ae3e0a7        32 minutes ago      19.6MB
chasdevs/meetrics    latest              98d54ae3e0a7        32 minutes ago      19.6MB
<none>               <none>              e2debd5d200f        32 minutes ago      1.02GB
mysql                latest              0f39f4b4d96c        12 hours ago        547MB
golang               latest              315fc470b445        7 days ago          809MB
alpine               latest              a187dde48cd2        3 weeks ago         5.6MB
aki-macbook-pro:meetrics akibalogh$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES```
